#############################################################################
# Makefile for building: ctisCarTool
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  ctisCarTool.pro
# Template: app
# Command: /home/xufq/Qt/5.15.2/gcc_64/bin/qmake -o Makefile ctisCarTool.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../5.15.2/gcc_64/include -I../../5.15.2/gcc_64/include/QtWidgets -I../../5.15.2/gcc_64/include/QtGui -I../../5.15.2/gcc_64/include/QtCore -I. -I/usr/include/libdrm -I. -I../../5.15.2/gcc_64/mkspecs/linux-g++
QMAKE         = /home/xufq/Qt/5.15.2/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/xufq/Qt/5.15.2/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/xufq/Qt/5.15.2/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ctisCarTool1.0.0
DISTDIR = /home/xufq/Qt/File/ctisCarTool/.tmp/ctisCarTool1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/xufq/Qt/5.15.2/gcc_64/lib
LIBS          = $(SUBLIBS) /home/xufq/Qt/5.15.2/gcc_64/lib/libQt5Widgets.so /home/xufq/Qt/5.15.2/gcc_64/lib/libQt5Gui.so /home/xufq/Qt/5.15.2/gcc_64/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = ../../5.15.2/gcc_64/mkspecs/features/spec_pre.prf \
		../../5.15.2/gcc_64/mkspecs/common/unix.conf \
		../../5.15.2/gcc_64/mkspecs/common/linux.conf \
		../../5.15.2/gcc_64/mkspecs/common/sanitize.conf \
		../../5.15.2/gcc_64/mkspecs/common/gcc-base.conf \
		../../5.15.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../5.15.2/gcc_64/mkspecs/common/g++-base.conf \
		../../5.15.2/gcc_64/mkspecs/common/g++-unix.conf \
		../../5.15.2/gcc_64/mkspecs/qconfig.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../5.15.2/gcc_64/mkspecs/features/qt_functions.prf \
		../../5.15.2/gcc_64/mkspecs/features/qt_config.prf \
		../../5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../5.15.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../5.15.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../5.15.2/gcc_64/mkspecs/features/toolchain.prf \
		../../5.15.2/gcc_64/mkspecs/features/default_pre.prf \
		../../5.15.2/gcc_64/mkspecs/features/resolve_config.prf \
		../../5.15.2/gcc_64/mkspecs/features/default_post.prf \
		../../5.15.2/gcc_64/mkspecs/features/warn_on.prf \
		../../5.15.2/gcc_64/mkspecs/features/qt.prf \
		../../5.15.2/gcc_64/mkspecs/features/resources_functions.prf \
		../../5.15.2/gcc_64/mkspecs/features/resources.prf \
		../../5.15.2/gcc_64/mkspecs/features/moc.prf \
		../../5.15.2/gcc_64/mkspecs/features/unix/opengl.prf \
		../../5.15.2/gcc_64/mkspecs/features/uic.prf \
		../../5.15.2/gcc_64/mkspecs/features/unix/thread.prf \
		../../5.15.2/gcc_64/mkspecs/features/qmake_use.prf \
		../../5.15.2/gcc_64/mkspecs/features/file_copies.prf \
		../../5.15.2/gcc_64/mkspecs/features/testcase_targets.prf \
		../../5.15.2/gcc_64/mkspecs/features/exceptions.prf \
		../../5.15.2/gcc_64/mkspecs/features/yacc.prf \
		../../5.15.2/gcc_64/mkspecs/features/lex.prf \
		ctisCarTool.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = ctisCarTool
DESTDIR       = 
TARGET        = ctisCarTool


first: all
####### Build rules

ctisCarTool: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ctisCarTool.pro ../../5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf ../../5.15.2/gcc_64/mkspecs/features/spec_pre.prf \
		../../5.15.2/gcc_64/mkspecs/common/unix.conf \
		../../5.15.2/gcc_64/mkspecs/common/linux.conf \
		../../5.15.2/gcc_64/mkspecs/common/sanitize.conf \
		../../5.15.2/gcc_64/mkspecs/common/gcc-base.conf \
		../../5.15.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../5.15.2/gcc_64/mkspecs/common/g++-base.conf \
		../../5.15.2/gcc_64/mkspecs/common/g++-unix.conf \
		../../5.15.2/gcc_64/mkspecs/qconfig.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../5.15.2/gcc_64/mkspecs/features/qt_functions.prf \
		../../5.15.2/gcc_64/mkspecs/features/qt_config.prf \
		../../5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../5.15.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../5.15.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../5.15.2/gcc_64/mkspecs/features/toolchain.prf \
		../../5.15.2/gcc_64/mkspecs/features/default_pre.prf \
		../../5.15.2/gcc_64/mkspecs/features/resolve_config.prf \
		../../5.15.2/gcc_64/mkspecs/features/default_post.prf \
		../../5.15.2/gcc_64/mkspecs/features/warn_on.prf \
		../../5.15.2/gcc_64/mkspecs/features/qt.prf \
		../../5.15.2/gcc_64/mkspecs/features/resources_functions.prf \
		../../5.15.2/gcc_64/mkspecs/features/resources.prf \
		../../5.15.2/gcc_64/mkspecs/features/moc.prf \
		../../5.15.2/gcc_64/mkspecs/features/unix/opengl.prf \
		../../5.15.2/gcc_64/mkspecs/features/uic.prf \
		../../5.15.2/gcc_64/mkspecs/features/unix/thread.prf \
		../../5.15.2/gcc_64/mkspecs/features/qmake_use.prf \
		../../5.15.2/gcc_64/mkspecs/features/file_copies.prf \
		../../5.15.2/gcc_64/mkspecs/features/testcase_targets.prf \
		../../5.15.2/gcc_64/mkspecs/features/exceptions.prf \
		../../5.15.2/gcc_64/mkspecs/features/yacc.prf \
		../../5.15.2/gcc_64/mkspecs/features/lex.prf \
		ctisCarTool.pro
	$(QMAKE) -o Makefile ctisCarTool.pro -spec linux-g++
../../5.15.2/gcc_64/mkspecs/features/spec_pre.prf:
../../5.15.2/gcc_64/mkspecs/common/unix.conf:
../../5.15.2/gcc_64/mkspecs/common/linux.conf:
../../5.15.2/gcc_64/mkspecs/common/sanitize.conf:
../../5.15.2/gcc_64/mkspecs/common/gcc-base.conf:
../../5.15.2/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../5.15.2/gcc_64/mkspecs/common/g++-base.conf:
../../5.15.2/gcc_64/mkspecs/common/g++-unix.conf:
../../5.15.2/gcc_64/mkspecs/qconfig.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3d_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../5.15.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../5.15.2/gcc_64/mkspecs/features/qt_functions.prf:
../../5.15.2/gcc_64/mkspecs/features/qt_config.prf:
../../5.15.2/gcc_64/mkspecs/linux-g++/qmake.conf:
../../5.15.2/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../5.15.2/gcc_64/mkspecs/features/exclusive_builds.prf:
../../5.15.2/gcc_64/mkspecs/features/toolchain.prf:
../../5.15.2/gcc_64/mkspecs/features/default_pre.prf:
../../5.15.2/gcc_64/mkspecs/features/resolve_config.prf:
../../5.15.2/gcc_64/mkspecs/features/default_post.prf:
../../5.15.2/gcc_64/mkspecs/features/warn_on.prf:
../../5.15.2/gcc_64/mkspecs/features/qt.prf:
../../5.15.2/gcc_64/mkspecs/features/resources_functions.prf:
../../5.15.2/gcc_64/mkspecs/features/resources.prf:
../../5.15.2/gcc_64/mkspecs/features/moc.prf:
../../5.15.2/gcc_64/mkspecs/features/unix/opengl.prf:
../../5.15.2/gcc_64/mkspecs/features/uic.prf:
../../5.15.2/gcc_64/mkspecs/features/unix/thread.prf:
../../5.15.2/gcc_64/mkspecs/features/qmake_use.prf:
../../5.15.2/gcc_64/mkspecs/features/file_copies.prf:
../../5.15.2/gcc_64/mkspecs/features/testcase_targets.prf:
../../5.15.2/gcc_64/mkspecs/features/exceptions.prf:
../../5.15.2/gcc_64/mkspecs/features/yacc.prf:
../../5.15.2/gcc_64/mkspecs/features/lex.prf:
ctisCarTool.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ctisCarTool.pro -spec linux-g++

qmake_all: FORCE


all: Makefile ctisCarTool

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../5.15.2/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../5.15.2/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h ../../5.15.2/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		../../5.15.2/gcc_64/include/QtWidgets/QMainWindow \
		../../5.15.2/gcc_64/include/QtWidgets/qmainwindow.h \
		../../5.15.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../5.15.2/gcc_64/include/QtGui/qtguiglobal.h \
		../../5.15.2/gcc_64/include/QtCore/qglobal.h \
		../../5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../5.15.2/gcc_64/include/QtCore/qconfig.h \
		../../5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		../../5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		../../5.15.2/gcc_64/include/QtCore/qlogging.h \
		../../5.15.2/gcc_64/include/QtCore/qflags.h \
		../../5.15.2/gcc_64/include/QtCore/qatomic.h \
		../../5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		../../5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../5.15.2/gcc_64/include/QtCore/qmutex.h \
		../../5.15.2/gcc_64/include/QtCore/qnumeric.h \
		../../5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		../../5.15.2/gcc_64/include/QtGui/qtgui-config.h \
		../../5.15.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../5.15.2/gcc_64/include/QtWidgets/qwidget.h \
		../../5.15.2/gcc_64/include/QtGui/qwindowdefs.h \
		../../5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../5.15.2/gcc_64/include/QtCore/qnamespace.h \
		../../5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../5.15.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../5.15.2/gcc_64/include/QtCore/qobject.h \
		../../5.15.2/gcc_64/include/QtCore/qstring.h \
		../../5.15.2/gcc_64/include/QtCore/qchar.h \
		../../5.15.2/gcc_64/include/QtCore/qbytearray.h \
		../../5.15.2/gcc_64/include/QtCore/qrefcount.h \
		../../5.15.2/gcc_64/include/QtCore/qarraydata.h \
		../../5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		../../5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../5.15.2/gcc_64/include/QtCore/qstringview.h \
		../../5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../5.15.2/gcc_64/include/QtCore/qlist.h \
		../../5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		../../5.15.2/gcc_64/include/QtCore/qiterator.h \
		../../5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../5.15.2/gcc_64/include/QtCore/qpair.h \
		../../5.15.2/gcc_64/include/QtCore/qvector.h \
		../../5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../5.15.2/gcc_64/include/QtCore/qpoint.h \
		../../5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../5.15.2/gcc_64/include/QtCore/qstringlist.h \
		../../5.15.2/gcc_64/include/QtCore/qregexp.h \
		../../5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		../../5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../5.15.2/gcc_64/include/QtCore/qmetatype.h \
		../../5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		../../5.15.2/gcc_64/include/QtCore/qmargins.h \
		../../5.15.2/gcc_64/include/QtGui/qpaintdevice.h \
		../../5.15.2/gcc_64/include/QtCore/qrect.h \
		../../5.15.2/gcc_64/include/QtCore/qsize.h \
		../../5.15.2/gcc_64/include/QtGui/qpalette.h \
		../../5.15.2/gcc_64/include/QtGui/qcolor.h \
		../../5.15.2/gcc_64/include/QtGui/qrgb.h \
		../../5.15.2/gcc_64/include/QtGui/qrgba64.h \
		../../5.15.2/gcc_64/include/QtGui/qbrush.h \
		../../5.15.2/gcc_64/include/QtGui/qmatrix.h \
		../../5.15.2/gcc_64/include/QtGui/qpolygon.h \
		../../5.15.2/gcc_64/include/QtGui/qregion.h \
		../../5.15.2/gcc_64/include/QtCore/qdatastream.h \
		../../5.15.2/gcc_64/include/QtCore/qiodevice.h \
		../../5.15.2/gcc_64/include/QtCore/qline.h \
		../../5.15.2/gcc_64/include/QtGui/qtransform.h \
		../../5.15.2/gcc_64/include/QtGui/qimage.h \
		../../5.15.2/gcc_64/include/QtGui/qpixelformat.h \
		../../5.15.2/gcc_64/include/QtGui/qpixmap.h \
		../../5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../5.15.2/gcc_64/include/QtCore/qshareddata.h \
		../../5.15.2/gcc_64/include/QtCore/qhash.h \
		../../5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../5.15.2/gcc_64/include/QtGui/qfont.h \
		../../5.15.2/gcc_64/include/QtGui/qfontmetrics.h \
		../../5.15.2/gcc_64/include/QtGui/qfontinfo.h \
		../../5.15.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../5.15.2/gcc_64/include/QtGui/qcursor.h \
		../../5.15.2/gcc_64/include/QtGui/qkeysequence.h \
		../../5.15.2/gcc_64/include/QtGui/qevent.h \
		../../5.15.2/gcc_64/include/QtCore/qvariant.h \
		../../5.15.2/gcc_64/include/QtCore/qmap.h \
		../../5.15.2/gcc_64/include/QtCore/qdebug.h \
		../../5.15.2/gcc_64/include/QtCore/qtextstream.h \
		../../5.15.2/gcc_64/include/QtCore/qlocale.h \
		../../5.15.2/gcc_64/include/QtCore/qset.h \
		../../5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../5.15.2/gcc_64/include/QtCore/qurl.h \
		../../5.15.2/gcc_64/include/QtCore/qurlquery.h \
		../../5.15.2/gcc_64/include/QtCore/qfile.h \
		../../5.15.2/gcc_64/include/QtCore/qfiledevice.h \
		../../5.15.2/gcc_64/include/QtGui/qvector2d.h \
		../../5.15.2/gcc_64/include/QtGui/qtouchdevice.h \
		../../5.15.2/gcc_64/include/QtWidgets/qtabwidget.h \
		../../5.15.2/gcc_64/include/QtGui/qicon.h \
		moc_predefs.h \
		../../5.15.2/gcc_64/bin/moc
	/home/xufq/Qt/5.15.2/gcc_64/bin/moc $(DEFINES) --include /home/xufq/Qt/File/ctisCarTool/moc_predefs.h -I/home/xufq/Qt/5.15.2/gcc_64/mkspecs/linux-g++ -I/home/xufq/Qt/File/ctisCarTool -I/home/xufq/Qt/5.15.2/gcc_64/include -I/home/xufq/Qt/5.15.2/gcc_64/include/QtWidgets -I/home/xufq/Qt/5.15.2/gcc_64/include/QtGui -I/home/xufq/Qt/5.15.2/gcc_64/include/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../5.15.2/gcc_64/bin/uic
	/home/xufq/Qt/5.15.2/gcc_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../5.15.2/gcc_64/include/QtWidgets/QMainWindow \
		../../5.15.2/gcc_64/include/QtWidgets/qmainwindow.h \
		../../5.15.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../5.15.2/gcc_64/include/QtGui/qtguiglobal.h \
		../../5.15.2/gcc_64/include/QtCore/qglobal.h \
		../../5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../5.15.2/gcc_64/include/QtCore/qconfig.h \
		../../5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		../../5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		../../5.15.2/gcc_64/include/QtCore/qlogging.h \
		../../5.15.2/gcc_64/include/QtCore/qflags.h \
		../../5.15.2/gcc_64/include/QtCore/qatomic.h \
		../../5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		../../5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../5.15.2/gcc_64/include/QtCore/qmutex.h \
		../../5.15.2/gcc_64/include/QtCore/qnumeric.h \
		../../5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		../../5.15.2/gcc_64/include/QtGui/qtgui-config.h \
		../../5.15.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../5.15.2/gcc_64/include/QtWidgets/qwidget.h \
		../../5.15.2/gcc_64/include/QtGui/qwindowdefs.h \
		../../5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../5.15.2/gcc_64/include/QtCore/qnamespace.h \
		../../5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../5.15.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../5.15.2/gcc_64/include/QtCore/qobject.h \
		../../5.15.2/gcc_64/include/QtCore/qstring.h \
		../../5.15.2/gcc_64/include/QtCore/qchar.h \
		../../5.15.2/gcc_64/include/QtCore/qbytearray.h \
		../../5.15.2/gcc_64/include/QtCore/qrefcount.h \
		../../5.15.2/gcc_64/include/QtCore/qarraydata.h \
		../../5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		../../5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../5.15.2/gcc_64/include/QtCore/qstringview.h \
		../../5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../5.15.2/gcc_64/include/QtCore/qlist.h \
		../../5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		../../5.15.2/gcc_64/include/QtCore/qiterator.h \
		../../5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../5.15.2/gcc_64/include/QtCore/qpair.h \
		../../5.15.2/gcc_64/include/QtCore/qvector.h \
		../../5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../5.15.2/gcc_64/include/QtCore/qpoint.h \
		../../5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../5.15.2/gcc_64/include/QtCore/qstringlist.h \
		../../5.15.2/gcc_64/include/QtCore/qregexp.h \
		../../5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		../../5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../5.15.2/gcc_64/include/QtCore/qmetatype.h \
		../../5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		../../5.15.2/gcc_64/include/QtCore/qmargins.h \
		../../5.15.2/gcc_64/include/QtGui/qpaintdevice.h \
		../../5.15.2/gcc_64/include/QtCore/qrect.h \
		../../5.15.2/gcc_64/include/QtCore/qsize.h \
		../../5.15.2/gcc_64/include/QtGui/qpalette.h \
		../../5.15.2/gcc_64/include/QtGui/qcolor.h \
		../../5.15.2/gcc_64/include/QtGui/qrgb.h \
		../../5.15.2/gcc_64/include/QtGui/qrgba64.h \
		../../5.15.2/gcc_64/include/QtGui/qbrush.h \
		../../5.15.2/gcc_64/include/QtGui/qmatrix.h \
		../../5.15.2/gcc_64/include/QtGui/qpolygon.h \
		../../5.15.2/gcc_64/include/QtGui/qregion.h \
		../../5.15.2/gcc_64/include/QtCore/qdatastream.h \
		../../5.15.2/gcc_64/include/QtCore/qiodevice.h \
		../../5.15.2/gcc_64/include/QtCore/qline.h \
		../../5.15.2/gcc_64/include/QtGui/qtransform.h \
		../../5.15.2/gcc_64/include/QtGui/qimage.h \
		../../5.15.2/gcc_64/include/QtGui/qpixelformat.h \
		../../5.15.2/gcc_64/include/QtGui/qpixmap.h \
		../../5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../5.15.2/gcc_64/include/QtCore/qshareddata.h \
		../../5.15.2/gcc_64/include/QtCore/qhash.h \
		../../5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../5.15.2/gcc_64/include/QtGui/qfont.h \
		../../5.15.2/gcc_64/include/QtGui/qfontmetrics.h \
		../../5.15.2/gcc_64/include/QtGui/qfontinfo.h \
		../../5.15.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../5.15.2/gcc_64/include/QtGui/qcursor.h \
		../../5.15.2/gcc_64/include/QtGui/qkeysequence.h \
		../../5.15.2/gcc_64/include/QtGui/qevent.h \
		../../5.15.2/gcc_64/include/QtCore/qvariant.h \
		../../5.15.2/gcc_64/include/QtCore/qmap.h \
		../../5.15.2/gcc_64/include/QtCore/qdebug.h \
		../../5.15.2/gcc_64/include/QtCore/qtextstream.h \
		../../5.15.2/gcc_64/include/QtCore/qlocale.h \
		../../5.15.2/gcc_64/include/QtCore/qset.h \
		../../5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../5.15.2/gcc_64/include/QtCore/qurl.h \
		../../5.15.2/gcc_64/include/QtCore/qurlquery.h \
		../../5.15.2/gcc_64/include/QtCore/qfile.h \
		../../5.15.2/gcc_64/include/QtCore/qfiledevice.h \
		../../5.15.2/gcc_64/include/QtGui/qvector2d.h \
		../../5.15.2/gcc_64/include/QtGui/qtouchdevice.h \
		../../5.15.2/gcc_64/include/QtWidgets/qtabwidget.h \
		../../5.15.2/gcc_64/include/QtGui/qicon.h \
		../../5.15.2/gcc_64/include/QtWidgets/QApplication \
		../../5.15.2/gcc_64/include/QtWidgets/qapplication.h \
		../../5.15.2/gcc_64/include/QtCore/qcoreapplication.h \
		../../5.15.2/gcc_64/include/QtCore/qeventloop.h \
		../../5.15.2/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../5.15.2/gcc_64/include/QtGui/qguiapplication.h \
		../../5.15.2/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../5.15.2/gcc_64/include/QtWidgets/QMainWindow \
		../../5.15.2/gcc_64/include/QtWidgets/qmainwindow.h \
		../../5.15.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../5.15.2/gcc_64/include/QtGui/qtguiglobal.h \
		../../5.15.2/gcc_64/include/QtCore/qglobal.h \
		../../5.15.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../5.15.2/gcc_64/include/QtCore/qconfig.h \
		../../5.15.2/gcc_64/include/QtCore/qtcore-config.h \
		../../5.15.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../5.15.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../5.15.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../5.15.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../5.15.2/gcc_64/include/QtCore/qsysinfo.h \
		../../5.15.2/gcc_64/include/QtCore/qlogging.h \
		../../5.15.2/gcc_64/include/QtCore/qflags.h \
		../../5.15.2/gcc_64/include/QtCore/qatomic.h \
		../../5.15.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../5.15.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../5.15.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../5.15.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../5.15.2/gcc_64/include/QtCore/qatomic_msvc.h \
		../../5.15.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../5.15.2/gcc_64/include/QtCore/qmutex.h \
		../../5.15.2/gcc_64/include/QtCore/qnumeric.h \
		../../5.15.2/gcc_64/include/QtCore/qversiontagging.h \
		../../5.15.2/gcc_64/include/QtGui/qtgui-config.h \
		../../5.15.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../5.15.2/gcc_64/include/QtWidgets/qwidget.h \
		../../5.15.2/gcc_64/include/QtGui/qwindowdefs.h \
		../../5.15.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../5.15.2/gcc_64/include/QtCore/qnamespace.h \
		../../5.15.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../5.15.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../5.15.2/gcc_64/include/QtCore/qobject.h \
		../../5.15.2/gcc_64/include/QtCore/qstring.h \
		../../5.15.2/gcc_64/include/QtCore/qchar.h \
		../../5.15.2/gcc_64/include/QtCore/qbytearray.h \
		../../5.15.2/gcc_64/include/QtCore/qrefcount.h \
		../../5.15.2/gcc_64/include/QtCore/qarraydata.h \
		../../5.15.2/gcc_64/include/QtCore/qstringliteral.h \
		../../5.15.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../5.15.2/gcc_64/include/QtCore/qstringview.h \
		../../5.15.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../5.15.2/gcc_64/include/QtCore/qlist.h \
		../../5.15.2/gcc_64/include/QtCore/qalgorithms.h \
		../../5.15.2/gcc_64/include/QtCore/qiterator.h \
		../../5.15.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../5.15.2/gcc_64/include/QtCore/qpair.h \
		../../5.15.2/gcc_64/include/QtCore/qvector.h \
		../../5.15.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../5.15.2/gcc_64/include/QtCore/qpoint.h \
		../../5.15.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../5.15.2/gcc_64/include/QtCore/qstringlist.h \
		../../5.15.2/gcc_64/include/QtCore/qregexp.h \
		../../5.15.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../5.15.2/gcc_64/include/QtCore/qcoreevent.h \
		../../5.15.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../5.15.2/gcc_64/include/QtCore/qmetatype.h \
		../../5.15.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../5.15.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../5.15.2/gcc_64/include/QtCore/qobject_impl.h \
		../../5.15.2/gcc_64/include/QtCore/qmargins.h \
		../../5.15.2/gcc_64/include/QtGui/qpaintdevice.h \
		../../5.15.2/gcc_64/include/QtCore/qrect.h \
		../../5.15.2/gcc_64/include/QtCore/qsize.h \
		../../5.15.2/gcc_64/include/QtGui/qpalette.h \
		../../5.15.2/gcc_64/include/QtGui/qcolor.h \
		../../5.15.2/gcc_64/include/QtGui/qrgb.h \
		../../5.15.2/gcc_64/include/QtGui/qrgba64.h \
		../../5.15.2/gcc_64/include/QtGui/qbrush.h \
		../../5.15.2/gcc_64/include/QtGui/qmatrix.h \
		../../5.15.2/gcc_64/include/QtGui/qpolygon.h \
		../../5.15.2/gcc_64/include/QtGui/qregion.h \
		../../5.15.2/gcc_64/include/QtCore/qdatastream.h \
		../../5.15.2/gcc_64/include/QtCore/qiodevice.h \
		../../5.15.2/gcc_64/include/QtCore/qline.h \
		../../5.15.2/gcc_64/include/QtGui/qtransform.h \
		../../5.15.2/gcc_64/include/QtGui/qimage.h \
		../../5.15.2/gcc_64/include/QtGui/qpixelformat.h \
		../../5.15.2/gcc_64/include/QtGui/qpixmap.h \
		../../5.15.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../5.15.2/gcc_64/include/QtCore/qshareddata.h \
		../../5.15.2/gcc_64/include/QtCore/qhash.h \
		../../5.15.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../5.15.2/gcc_64/include/QtGui/qfont.h \
		../../5.15.2/gcc_64/include/QtGui/qfontmetrics.h \
		../../5.15.2/gcc_64/include/QtGui/qfontinfo.h \
		../../5.15.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../5.15.2/gcc_64/include/QtGui/qcursor.h \
		../../5.15.2/gcc_64/include/QtGui/qkeysequence.h \
		../../5.15.2/gcc_64/include/QtGui/qevent.h \
		../../5.15.2/gcc_64/include/QtCore/qvariant.h \
		../../5.15.2/gcc_64/include/QtCore/qmap.h \
		../../5.15.2/gcc_64/include/QtCore/qdebug.h \
		../../5.15.2/gcc_64/include/QtCore/qtextstream.h \
		../../5.15.2/gcc_64/include/QtCore/qlocale.h \
		../../5.15.2/gcc_64/include/QtCore/qset.h \
		../../5.15.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../5.15.2/gcc_64/include/QtCore/qurl.h \
		../../5.15.2/gcc_64/include/QtCore/qurlquery.h \
		../../5.15.2/gcc_64/include/QtCore/qfile.h \
		../../5.15.2/gcc_64/include/QtCore/qfiledevice.h \
		../../5.15.2/gcc_64/include/QtGui/qvector2d.h \
		../../5.15.2/gcc_64/include/QtGui/qtouchdevice.h \
		../../5.15.2/gcc_64/include/QtWidgets/qtabwidget.h \
		../../5.15.2/gcc_64/include/QtGui/qicon.h \
		ui_mainwindow.h \
		../../5.15.2/gcc_64/include/QtCore/QVariant \
		../../5.15.2/gcc_64/include/QtWidgets/QApplication \
		../../5.15.2/gcc_64/include/QtWidgets/qapplication.h \
		../../5.15.2/gcc_64/include/QtCore/qcoreapplication.h \
		../../5.15.2/gcc_64/include/QtCore/qeventloop.h \
		../../5.15.2/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../5.15.2/gcc_64/include/QtGui/qguiapplication.h \
		../../5.15.2/gcc_64/include/QtGui/qinputmethod.h \
		../../5.15.2/gcc_64/include/QtWidgets/QMenuBar \
		../../5.15.2/gcc_64/include/QtWidgets/qmenubar.h \
		../../5.15.2/gcc_64/include/QtWidgets/qmenu.h \
		../../5.15.2/gcc_64/include/QtWidgets/qaction.h \
		../../5.15.2/gcc_64/include/QtWidgets/qactiongroup.h \
		../../5.15.2/gcc_64/include/QtWidgets/QPushButton \
		../../5.15.2/gcc_64/include/QtWidgets/qpushbutton.h \
		../../5.15.2/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../5.15.2/gcc_64/include/QtWidgets/QStatusBar \
		../../5.15.2/gcc_64/include/QtWidgets/qstatusbar.h \
		../../5.15.2/gcc_64/include/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/ctisCarTool/bin || mkdir -p $(INSTALL_ROOT)/opt/ctisCarTool/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/ctisCarTool/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/ctisCarTool/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/ctisCarTool/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ctisCarTool/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

