(cl:in-package localization-msg)
(cl:export '(FPD_HEADER-VAL
          FPD_HEADER
          FPD_GPSWEEK-VAL
          FPD_GPSWEEK
          FPD_GPSTIME-VAL
          FPD_GPSTIME
          HEADING-VAL
          HEADING
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          LATTITUDE-VAL
          LATTITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          VE-VAL
          VE
          VN-VAL
          VN
          VU-VAL
          VU
          BASELINE-VAL
          BASELINE
          NSV1-VAL
          NSV1
          NSV2-VAL
          NSV2
          STATUS-VAL
          STATUS
          FPD_CS-VAL
          FPD_CS
          IMU_HEADER-VAL
          IMU_HEADER
          IMU_GPSWEEK-VAL
          IMU_GPSWEEK
          IMU_GPSTIME-VAL
          IMU_GPSTIME
          GYROX-VAL
          GYROX
          GYROY-VAL
          GYROY
          GYROZ-VAL
          GYROZ
          ACCX-VAL
          ACCX
          ACCY-VAL
          ACCY
          ACCZ-VAL
          ACCZ
          TPR-VAL
          TPR
          IMU_CS-VAL
          IMU_CS
          X-VAL
          X
          Y-VAL
          Y
))